name: Tests and docs

on: [push, pull_request]

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run unit tests
      run: mvn test

  integration_test:
    name: Integration tests
    needs: unit_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]
        db: [ h2, hsqldb, mysql, postgres, mongo ]

    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_DATABASE: testdb
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:9.6-bullseye
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      mongo:
        image: mongo:5.0.3
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres
        ports:
          - 27017:27017
        options: >-
          --health-cmd=mongo
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run up to integration tests
      run: mvn clean verify -P default,${{ matrix.db }} -Dtest.environment=${{ matrix.db }}

  deploy_develop_docs:
    name: Deploy development docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@v1
    with:
      branch: develop
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
      username: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
      password: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@v1
    with:
      branch: master
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_SITE }}
      username: ${{ secrets.DEPLOY_DOCS_USER }}
      password: ${{ secrets.DEPLOY_DOCS_PASSWORD }}